# Generated by Django 5.0.3 on 2024-12-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cat_type',
            field=models.TextField(default='tuxedo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='happiness',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hunger',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sleep',
            field=models.FloatField(default=100),
        ),
    ]
